### ISSUE TITLE
Bluetooth device control doesn't work

### ISSUE THREAD

**Issue by JaniHuuskonen** [denniedegroot/com.luke.roberts#5]
I'm trying to add Luke Roberts Luvo-light into Homey Pro 2023.
Homey finds and adds the device, but when trying to control the light from Homey, nothing happens.

Adding device via cloud connection works but control is unreliable, but I think this is due to Luke Roberts cloud connection itself which is unreliable anyway.

Could you please look into this, the Luke Roberts light itself is magnificient except for their the decision to make control connection work only via bluetooth which makes very difficult to include it to home automations. Purchasing Homey Pro over Home Assistant was mainly because Athom themselves advertise Luke Roberts support.

Luke Roberts Luvo information:
Lamp model ID: LRF01C
Lamp FW version: 1.2.2
Lamp BL version: 2 (HK 0)

Homey Pro information:
Model: Homey Pro (Early 2023)
Version: 12.0.0

Application diagnostics report:
30a566ca-74d3-4451-8941-cf53f84b12ff

**Comment by denniedegroot** [comment]
Could you try to place the Homey closer to the light and try again? 
The Bluetooth module in Homey 2023 is very frustrating to say the least.

**Comment by denniedegroot** [comment]
Looking at the diagnostics report I see (many) Homey core related errors, they are all the same error though.
I cannot solve/debug these, you could try to reinstall the app. If this still doesn't work you could contact Homey support and use the snippet below:

> 2024-08-16T09:37:45.400Z [log] [ManagerDrivers] [Driver:smart-lamp] [Device:27ad8bc8-7877-4577-8a4d-9a967b9b890f] Error: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" doesn't exist
>     at Remote Process
>     at HomeyClient.emit (/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23)
>     at Object.emit (/node_modules/@athombv/homey-apps-sdk-v3/manager/ble.js:119:32)
>     at BlePeripheral.discoverAllServicesAndCharacteristics (/node_modules/@athombv/homey-apps-sdk-v3/lib/BlePeripheral.js:212:25)
>     at SmartLampDevice._getService (/app/drivers/smart-lamp/device.js:110:26)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async SmartLampDevice._processQueue (/app/drivers/smart-lamp/device.js:167:20)

**Comment by JaniHuuskonen** [comment]
> Could you try to place the Homey closer to the light and try again? The Bluetooth module in Homey 2023 is very frustrating to say the least.

Thank you for the very fast response!
Homey is in the same room as Luvo with approximately 3 meters distance and with direct line of sight, I don't the distance is the issue here.

**Comment by JaniHuuskonen** [comment]
> Looking at the diagnostics report I see (many) Homey core related errors, they are all the same error though. I cannot solve/debug these, you could try to reinstall the app. If this still doesn't work you could contact Homey support and use the snippet below:
> 
> > 2024-08-16T09:37:45.400Z [log] [ManagerDrivers] [Driver:smart-lamp] [Device:27ad8bc8-7877-4577-8a4d-9a967b9b890f] Error: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" doesn't exist
> > at Remote Process
> > at HomeyClient.emit (/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23)
> > at Object.emit (/node_modules/@athombv/homey-apps-sdk-v3/manager/ble.js:119:32)
> > at BlePeripheral.discoverAllServicesAndCharacteristics (/node_modules/@athombv/homey-apps-sdk-v3/lib/BlePeripheral.js:212:25)
> > at SmartLampDevice._getService (/app/drivers/smart-lamp/device.js:110:26)
> > at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> > at async SmartLampDevice._processQueue (/app/drivers/smart-lamp/device.js:167:20)

Reinstallation doesn't help, I'll try to contact Athoms support.
Thanks!

**Comment by goldenstarshine** [comment]
@JaniHuuskonen I am currently setting up a newly bought Homey Pro (2023), and would like to control my Luke Roberts lamps with it as well. I am running into the same issue(s) which you have initially described above. 
Were you able to sort out the issues via Athoms Support? Can you now effectively control your Luke Roberts lamps?
Thank you in advance for your reply!

**Comment by JaniHuuskonen** [comment]
Unfortunately no luck with Athom support either.
Luke Roberts own cloud service was too down for a long time, their support
promised to return to me when their issues have been solved but no
communication from their part either unless asked again. I haven't tried
that in a few weeks now since it seems strongly that the only reliable way
to control the lamp is a local connection.
Their support didn't either answer to my question do they have plans for
thread support.

It's a shame, I just love the lamp itself, but it seems that it just isn't
designed to be controlled in any other way than manually from the app.

**Comment by goldenstarshine** [comment]
Many thanks @JaniHuuskonen for your quick reply and the details. 
I'll try my luck and will contact both the manufacturer of the lamp, as well as Athom - I will keep you posted.

**Comment by HerrEck** [comment]
Same problem here. With my older Homey, the lamp worked quite well since 2019. So i did not foreseen that it would not anymore with my new homey pro :(. Any updates from you side?

**Comment by HerrEck** [comment]
The Athom support sends me back to the developer. Is there anything i can provide Athom to look for?

**Comment by HerrEck** [comment]
Is this app dead? No support here :(?

**Comment by denniedegroot** [comment]
There is nothing I can do with the app. The BLE of the Homey 2023 is just not working correctly.
For BLE I still use my old Homey 2019 next to my Homey 2023...
